# ----------
# dataset
# ----------
data_root: ./dataset/
n_classes: 21
classes: ['aeroplane', 'bicycle', 'bird', 'boat',
          'bottle', 'bus', 'car', 'cat', 'chair',
          'cow', 'diningtable', 'dog', 'horse',
          'motorbike', 'person', 'pottedplant',
          'sheep', 'sofa', 'train', 'tvmonitor']
img_size: 300
n_channels: 3
color_mean: [104, 117, 123]
train_txt: train.txt
test_txt: val.txt

# ----------------
# train parameters
# ----------------
lr: 0.0001
decay: 1e-4
n_gpus: 1
batch_size: 64
n_epochs: 50
jaccord_thresh: 0.5
neg_pos: 3

# pretrained path: vgg16 model path or blank
pretrained: /home/rizawa/Codes/playing/ML/SSD/weights/vgg16_reducedfc.pth

# ssd configs
bbox_aspect_num: [4, 6, 6, 6, 4, 4]  # number of aspect ratios of dbox
feature_maps: [38, 19, 10, 5, 3, 1]  # feature map size of each source
steps: [8, 16, 32, 64, 100, 300]  # size of dbox
min_sizes: [30, 60, 111, 162, 213, 264]  # size of dbox
max_sizes: [60, 111, 162, 213, 264, 315]  # size of dbox
aspect_ratios: [[2], [2, 3], [2, 3], [2, 3], [2], [2]] # aspect ratios
variances: [0.1, 0.2] # variances for decode
conf_thresh: 0.01
top_k: 200
nms_thresh: 0.45

# metric configs
confidence_level: 0.5

# save_ckpt_interval should not be 0.
save_ckpt_interval: 50

# output dir (logs, results)
log_dir: ./logs/

# checkpoint path or blank
resume: /home/rizawa/Codes/playing/ML/SSD/weights/ssd300_50.pth
# e.g) resume: ./logs/2020-07-26T00:19:34.918002/ckpt/best_acc_ckpt.pth